# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/flywcs/myData/myCode/python-clone-workspace/pythonCodeFactory/ui/mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(1167, 635)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, -20, 1161, 140))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.txtDBUrl = QtWidgets.QTextEdit(self.groupBox)
        self.txtDBUrl.setGeometry(QtCore.QRect(10, 30, 1141, 61))
        self.txtDBUrl.setObjectName("txtDBUrl")
        self.btnOpenDB = QtWidgets.QPushButton(self.groupBox)
        self.btnOpenDB.setGeometry(QtCore.QRect(350, 100, 90, 27))
        self.btnOpenDB.setObjectName("btnOpenDB")
        self.btnMakeCode = QtWidgets.QPushButton(self.groupBox)
        self.btnMakeCode.setGeometry(QtCore.QRect(450, 100, 90, 27))
        self.btnMakeCode.setObjectName("btnMakeCode")
        self.cbxDBAdapters = QtWidgets.QComboBox(self.groupBox)
        self.cbxDBAdapters.setGeometry(QtCore.QRect(10, 100, 331, 27))
        self.cbxDBAdapters.setObjectName("cbxDBAdapters")
        self.btnMakeAllCode = QtWidgets.QPushButton(self.groupBox)
        self.btnMakeAllCode.setGeometry(QtCore.QRect(550, 100, 151, 27))
        self.btnMakeAllCode.setObjectName("btnMakeAllCode")
        self.btnHelp = QtWidgets.QPushButton(self.groupBox)
        self.btnHelp.setGeometry(QtCore.QRect(710, 100, 51, 27))
        self.btnHelp.setObjectName("btnHelp")
        self.tvTables = QtWidgets.QTreeView(self.centralwidget)
        self.tvTables.setGeometry(QtCore.QRect(10, 130, 341, 470))
        self.tvTables.setObjectName("tvTables")
        self.twPages = QtWidgets.QTabWidget(self.centralwidget)
        self.twPages.setGeometry(QtCore.QRect(360, 130, 801, 470))
        self.twPages.setObjectName("twPages")
        self.tabNormal = QtWidgets.QWidget()
        self.tabNormal.setObjectName("tabNormal")
        self.txtNormalText = QtWidgets.QPlainTextEdit(self.tabNormal)
        self.txtNormalText.setGeometry(QtCore.QRect(10, 10, 781, 421))
        self.txtNormalText.setReadOnly(True)
        self.txtNormalText.setObjectName("txtNormalText")
        self.twPages.addTab(self.tabNormal, "")
        self.tabEntityAndDAO = QtWidgets.QWidget()
        self.tabEntityAndDAO.setObjectName("tabEntityAndDAO")
        self.txtEntityAndDAOText = QtWidgets.QPlainTextEdit(self.tabEntityAndDAO)
        self.txtEntityAndDAOText.setGeometry(QtCore.QRect(10, 10, 781, 421))
        self.txtEntityAndDAOText.setReadOnly(True)
        self.txtEntityAndDAOText.setObjectName("txtEntityAndDAOText")
        self.twPages.addTab(self.tabEntityAndDAO, "")
        self.tabNormalScript = QtWidgets.QWidget()
        self.tabNormalScript.setObjectName("tabNormalScript")
        self.txtNormalScript = QtWidgets.QTextEdit(self.tabNormalScript)
        self.txtNormalScript.setGeometry(QtCore.QRect(10, 40, 781, 391))
        self.txtNormalScript.setObjectName("txtNormalScript")
        self.btnSaveNormalScript = QtWidgets.QPushButton(self.tabNormalScript)
        self.btnSaveNormalScript.setGeometry(QtCore.QRect(700, 10, 87, 27))
        self.btnSaveNormalScript.setObjectName("btnSaveNormalScript")
        self.twPages.addTab(self.tabNormalScript, "")
        self.tabEntityAndDAOScript = QtWidgets.QWidget()
        self.tabEntityAndDAOScript.setObjectName("tabEntityAndDAOScript")
        self.btnSaveEntityAndDAOScript = QtWidgets.QPushButton(self.tabEntityAndDAOScript)
        self.btnSaveEntityAndDAOScript.setGeometry(QtCore.QRect(700, 10, 87, 27))
        self.btnSaveEntityAndDAOScript.setObjectName("btnSaveEntityAndDAOScript")
        self.txtEntityAndDAOScript = QtWidgets.QTextEdit(self.tabEntityAndDAOScript)
        self.txtEntityAndDAOScript.setGeometry(QtCore.QRect(10, 40, 781, 391))
        self.txtEntityAndDAOScript.setObjectName("txtEntityAndDAOScript")
        self.twPages.addTab(self.tabEntityAndDAOScript, "")
        self.btnConfigEditor = QtWidgets.QWidget()
        self.btnConfigEditor.setObjectName("btnConfigEditor")
        self.btnSaveConfig = QtWidgets.QPushButton(self.btnConfigEditor)
        self.btnSaveConfig.setGeometry(QtCore.QRect(700, 10, 87, 27))
        self.btnSaveConfig.setObjectName("btnSaveConfig")
        self.txtConfig = QtWidgets.QTextEdit(self.btnConfigEditor)
        self.txtConfig.setGeometry(QtCore.QRect(10, 40, 781, 391))
        self.txtConfig.setObjectName("txtConfig")
        self.twPages.addTab(self.btnConfigEditor, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1167, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.twPages.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "简易数据库代码生成器V1.0"))
        self.btnOpenDB.setText(_translate("MainWindow", "打开数据库"))
        self.btnMakeCode.setText(_translate("MainWindow", "生成代码"))
        self.btnMakeAllCode.setText(_translate("MainWindow", "生成所有代码到文件"))
        self.btnHelp.setText(_translate("MainWindow", "关于"))
        self.tabNormal.setProperty("currentTabText", _translate("MainWindow", "常用代码"))
        self.twPages.setTabText(self.twPages.indexOf(self.tabNormal), _translate("MainWindow", "常用代码"))
        self.tabEntityAndDAO.setProperty("currentTabText", _translate("MainWindow", "fff"))
        self.twPages.setTabText(self.twPages.indexOf(self.tabEntityAndDAO), _translate("MainWindow", "实体和DAO"))
        self.btnSaveNormalScript.setText(_translate("MainWindow", "保存"))
        self.twPages.setTabText(self.twPages.indexOf(self.tabNormalScript), _translate("MainWindow", "编辑常用代码脚本"))
        self.btnSaveEntityAndDAOScript.setText(_translate("MainWindow", "保存"))
        self.twPages.setTabText(self.twPages.indexOf(self.tabEntityAndDAOScript), _translate("MainWindow", "编辑实体和DAO代码脚本"))
        self.btnSaveConfig.setText(_translate("MainWindow", "保存"))
        self.twPages.setTabText(self.twPages.indexOf(self.btnConfigEditor), _translate("MainWindow", "编辑配置文件"))
